name: E2E

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-commit-hook:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Run check-commit-hook.sh
        run: |
          chmod +x e2e/check-commit-hook.sh
          ./e2e/check-commit-hook.sh